name: Compile python to binary

on:
  push:
    branches: [ master ]
  schedule:
  - cron: "47 22 4 * *"


jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-11.0, macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Run pyinstaller
      run: |
        pyinstaller --onefile canvasGrades.py
    - uses: actions/upload-artifact@v2
      with:
        name: canvasGrades-${{ matrix.os }}
        path: dist/**
