# Compiles python into executable files for macos, linux, and windows

name: Compile python to binary

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Find and replace VERSIONNUM with the actual version number
      uses: datamonsters/replace-action@v2
      with:
        files: canvasGrades.py 
        replacements: "VERSIONNUM=${{ github.run_number }}"
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Run pyinstaller
      run: |
        pyinstaller --onefile canvasGrades.py
    - uses: actions/upload-artifact@v2
      with:
        name: canvasGrades-${{ runner.os }}
        path: dist/**
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: AUTO-${{ github.run_number }}
          release_name: "[AUTO] Build ${{ github.run_number }}"
          body: |
            New build!
            Check out https://github.com/burturt/canvas-scripts/commits/master to see changes
            If you want to run the program yourself, download one of the files under "Assets" with the name of your operating system.
          draft: false
          prerelease: false
      - uses: actions/download-artifact@v2
        name: Download artifacts
      - name: Display structure of downloaded files
        run: ls -R
      - name: Zip artifacts
        run: |
          chmod +x canvasGrades-Linux/canvasGrades
          chmod +x canvasGrades-macOS/canvasGrades
          zip -r canvasGrades-Linux-${{ github.run_number }}.zip canvasGrades-Linux
          zip -r canvasGrades-Windows-${{ github.run_number }}.zip canvasGrades-Windows
          zip -r canvasGrades-MacOS-${{ github.run_number }}.zip canvasGrades-macOS
      - name: Upload Linux Build
        id: upload-linux
        uses: actions/upload-release-asset@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: canvasGrades-Linux-${{ github.run_number }}.zip
          asset_name: canvasGrades-Linux-${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Upload Windows Build
        id: upload-windows
        uses: actions/upload-release-asset@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: canvasGrades-Windows-${{ github.run_number }}.zip
          asset_name: canvasGrades-Windows-${{ github.run_number }}.zip
          asset_content_type: application/zip
          
      - name: Upload MacOS Build
        id: upload-macos
        uses: actions/upload-release-asset@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: canvasGrades-MacOS-${{ github.run_number }}.zip
          asset_name: canvasGrades-MacOS-${{ github.run_number }}.zip
          asset_content_type: application/zip
